---
################################################
# Setup a brand new MacOS out of the box
#
# inspired by
#   - https://gist.github.com/mrlesmithjr/f3c15fdd53020a71f55c2032b8be2eda
################################################
- name: Setup development environment for MacOS
  hosts: all

  collections:
    - provision.pkg

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Homebrew is missing...Installing from http://brew.sh
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not homebrew_check.stat.exists

  roles:
    - sublime

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists
 
  #  - name: Installing Homebrew Cask Packages
  #    homebrew_cask:
  #      name: "{{ brew_cask_packages }}"
  #      state: present
  #    register: result
  #    until: result is successful
  #    when: homebrew_check.stat.exists

    - name: Install tree package
      homebrew:
        name: tree
        state: present

  #  - name: Install helix package
  #    homebrew:
  #      name: helix
  #      state: present

    #- name: Install DMG Packages
    #  dmg:
    #    name: "Motrix"
    #    path: "~/Downloads/Motrix-1.6.11.dmg"
