---
# Install package via homebrew on MacOS when
# community-general galaxy collection is installed
- name: Install NeoVim
  package:
    name: neovim
    state: present

- name: Set Variables
  set_fact:
    home: "{{ lookup('env', 'HOME') }}"

- name: Debug ENV
  debug:
    msg: "HOME={{ home }}"

- name: Create .config Folder
  file:
    path: "{{ home }}/.config" 
    state: directory
    recurse: true

- name: Copy Configuration Files
  copy:
    src: nvim
    dest: "{{ home }}/.config/"
